# Generated by Django 3.0.4 on 2020-03-21 15:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('products', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=609, size=29)),
            ],
        ),
    ]
