# Generated by Django 3.0.4 on 2020-03-22 10:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='products',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=189, size=9),
        ),
    ]
