# Generated by Django 3.0.4 on 2020-03-22 11:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200322_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(verbose_name='date_purchased'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='products',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10),
        ),
    ]
